name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# 1. This cancels the Actions job immediately when a new one starts
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # ... your jobs ...
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
